 #server:
#  port: 8080
##  servlet:
##    context-path: /department-system
#
#spring:
#  datasource:
#    url: 'jdbc:postgresql://localhost:5432/department'
#    username: postgres
#    password: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "http://localhost:5173/auth/google/callback"
#        provider:
#          google:
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#      resourceserver:
#        opaque:
#          introspection-uri: "https://googleapis.com"
#
#authentication:
#  jwt:
#    base64-secret: 2s+qtEY90ymZ/PQhalri+aL2yI7084rVyTtU4ykYD+8/I4MNfUhd2gwlVRAB28MOMOkMtXxys2ALGvI8qSZgJw==
#    access-token-validity-in-seconds: 36000
#    refresh-token-validity-in-seconds: 86400


server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/department'
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

authentication:
  jwt:
    base64-secret: 2s+qtEY90ymZ/PQhalri+aL2yI7084rVyTtU4ykYD+8/I4MNfUhd2gwlVRAB28MOMOkMtXxys2ALGvI8qSZgJw==
    access-token-validity-in-seconds: 36000
    refresh-token-validity-in-seconds: 86400
